### ISSUE TITLE
Marked as Trojan by NANO-Antivirus on VT

### ISSUE THREAD

**Issue by RatoGBM** [Drew-Alleman/DataSurgeon#1]
<img width="554" alt="Screenshot 2023-03-04 at 20 35 45" src="https://user-images.githubusercontent.com/80184495/222936852-41ec0e2b-90cf-4f64-b10d-3664a358a3ba.png">

Virus Total

fb78292fc758b2cbb0256bdc4df1e2f2a5019bed29938c1d3134528a28610d92

**Comment by Drew-Alleman** [comment]
What did you scan?
What is the link to the full scan?
This is open source software if you are really concerned, read the source. There is plenty of software that return as malware.

**Comment by RatoGBM** [comment]
I download everything as zip 
<img width="526" alt="Screenshot 2023-03-04 at 21 15 33" src="https://user-images.githubusercontent.com/80184495/222938001-956fb850-2ddd-494b-8daa-d6496c3cd62b.png">
And just punched it into https://www.virustotal.com/gui/home/upload

**Comment by Drew-Alleman** [comment]
Thanks for confirming! The NANO-Antivirus detected the README.md as malware due to the quick installers. The actual install scripts and DS were not flagged. I am marking this as resolved, unless you have any further questions.
1. Readme: ->https://www.virustotal.com/gui/file/af2545d1fe81211926ec79a53d8cbb59a1105b7e11d61796d6cb2bae98d03c68?nocache=1
2. install.ps1 -> https://www.virustotal.com/gui/file/0b051e95c69635fe330415518e702fece39c8c3da1111a4d76edbfdcb95b567d
3. install.sh -> https://www.virustotal.com/gui/file/5783f15d1eb5c21dcf86cc3c53bacddf27cdeb91b9a36d01e43820ddb7b5e845?nocache=1
4. ds.exe -> https://www.virustotal.com/gui/file-analysis/ZGViYzkxNDNiYjlkYTUxZjQ2MjU4NTM5OGYyMTczMTM6MTY3Nzk4MzEyNw==
